name: Main Workflow Dispatcher

on: [push, pull_request]

jobs:
  setup_docker:
    runs-on: ubuntu-latest
    steps:
      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r '.tag_name')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

  sync_job:
    needs: setup_docker
    uses: ./.github/workflows/sync.yml  # References sync.yml in the workflows directory

  test_job:
    needs: sync_job  # Runs after sync_job completes
    uses: ./.github/workflows/test.yml  # References test.yml in the workflows directory
