name: Test cookiecutter scaffolder

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        experimental_use_app_router: [
          {name: "Page router", value: "False"},
          {name: "App router", value: "True"},
        ]

    steps:
      - uses: actions/checkout@v4

      # Set up Docker Compose
      - name: Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K[^"]+')" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      # Sync changes from Company-Project to cookiecutter
      - name: Make sync.sh executable
        run: chmod +x .github/workflows/sync.sh

      - name: Sync changes from Company-Project to cookiecutter
        run: .github/workflows/sync.sh

      # Continue with testing steps
      - uses: "actions/setup-python@v5"
        with:
          python-version: "3.11"
      - name: Install cookiecutter
        run: |
          python -m pip install --upgrade pip
          pip install cookiecutter
      - name: Cleanup
        run: |
          set -x
          rm -rf Company-Project
      - name: Run cookiecutter
        run: |
          cookiecutter . --no-input experimental_use_app_router=${{ matrix.experimental_use_app_router.value }}
      - name: Create docker-compose config for running boilerplate tests
        run: |
          cp docker-compose-ci.yml Company-Project/docker-compose-ci.yml
      - name: Build image
        run: |
          cd Company-Project
          chmod +x src/docker-entrypoint.sh
          docker-compose -f docker-compose-ci.yml build
      - name: Verify backend scaffolder
        run: |
          cd Company-Project
          set -x
          docker-compose -f docker-compose-ci.yml run --rm python python manage.py new_page --name=Article
      - name: Run tests on container
        run: |
          cd Company-Project
          docker-compose -f docker-compose-ci.yml run --rm python test
          docker-compose -f docker-compose-ci.yml run --rm python typecheck
          docker-compose -f docker-compose-ci.yml run --rm python lint
      - name: Run frontend tests
        run: |
          cd Company-Project/frontend
          npm ci
          npm run test:ci
          IGNORE_SENTRY=1 npm run build
          npm run build-storybook
