name: Main Workflow Dispatcher

on: [push, pull_request]

jobs:
  sync_job:
    uses: ./.github/workflows/sync.yml  # References sync.yml in the workflows directory

  test_job:
    needs: sync_job  # Runs after sync_job completes
    uses: ./.github/workflows/test.yml  # References test.yml in the workflows directory
