name: Sync Company-Project to {{cookiecutter.project_name}}

on:
  workflow_call:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install jq (for JSON parsing)
        run: sudo apt-get install -y jq

      - name: Make sync.sh executable
        run: chmod +x .github/workflows/sync.sh

      - name: Run sync script
        run: .github/workflows/sync.sh

      # Optionally, push changes to a new branch and create a PR if necessary
      - name: Set up git for committing changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Push changes to a new branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b sync-changes
          git add {{cookiecutter.project_name}}/
          git commit -m "Sync updates from Company-Project to {{cookiecutter.project_name}}"
          git push origin sync-changes

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: sync-changes
          title: "Sync updates from Company-Project to {{cookiecutter.project_name}}"
          body: "This PR syncs changes from Company-Project to {{cookiecutter.project_name}}."
